version: '3.3'
services:
  traefik:
    image: "traefik:v2.2"
    networks:
      - traefik-public
    command:
      - '--providers.docker=true'
      - '--entryPoints.web.address=:80'
      - '--providers.providersThrottleDuration=2s'
      - '--providers.docker.watch=true'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.swarmModeRefreshSeconds=15s'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.defaultRule=Host("localhost")'
      - '--accessLog.bufferingSize=0'
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  covid-frontend:
    image: covid-frontend:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covid-frontend.rule=Host(`localhost`)"
        - "traefik.http.routers.covid-frontend.entrypoints=web"
        - traefik.http.services.covid-frontend.loadbalancer.server.port=9000
        - "traefik.docker.network=traefik-public"
        - traefik.covid-frontend.loadbalancer.swarm=true
    depends_on:
      - traefik
  covid-api:
    image: covid-api:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covid-api.entrypoints=web"
        - traefik.http.routers.covid-api.rule=PathPrefix(`/api`)
        - traefik.http.services.covid-api.loadbalancer.server.port=8000
        - "traefik.docker.network=traefik-public"
        - traefik.covid-api.loadbalancer.swarm=true
    depends_on:
      - traefik

networks:
  traefik-public:
    external: true
