apiVersion: v1
kind: Service
metadata:
  name: covid-api
spec:
  type: NodePort
  selector:
    app: covid-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-api
  template:
    metadata:
      labels:
        app: covid-api
    spec:
      containers:
        - name: covid-api
          image: williamvelazquez/covid-api:initial
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
