apiVersion: v1
kind: Service
metadata:
  name: covid-proxy
spec:
  type: NodePort
  selector:
    app: covid-proxy
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-proxy
  template:
    metadata:
      labels:
        app: covid-proxy
    spec:
      containers:
        - name: covid-proxy
          image: williamvelazquez/covid-proxy:initial
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf # mount nginx-conf volumn to /etc/nginx
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            # items:
            #   - key: nginx.conf
            #     path: nginx.conf
