apiVersion: v1
kind: Service
metadata:
  name: covid-frontend
spec:
  type: NodePort
  selector:
    app: covid-frontend
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-frontend
  template:
    metadata:
      labels:
        app: covid-frontend
    spec:
      containers:
        - name: covid-frontend
          image: covid-frontend
          ports:
            - containerPort: 9000
          env:
            - name: API_URL
              value: http://localhost:8000/
          imagePullPolicy: Never

